### ISSUE TITLE
Backup course

### ISSUE THREAD

**Issue by litall** [dkuzevanov/moodle_master_slave#1]
After I changed my config.php file to work with mysql-ms
I can't backup courses.
I get error "Table 'moodle_moodle_f.backup_ids_temp' doesn't exist"

**Comment by dkuzevanov** [comment]
Hello!

I think the reason is replication speed — Moodle tries to make temporary table and then to read from it (but it's not replicated yet). Don't you have replication lag?
Can you describe your actions step by step?

I will test this and then write what can you do in this situation.

**Comment by dkuzevanov** [comment]
This bug is related to **/backup/util/dbops/backup_question_dbops.class.php**

**Comment by dkuzevanov** [comment]
You can use this patch — [backup_question_dbops.class.php.patch.txt](https://github.com/dkuzevanov/moodle_master_slave/files/401241/backup_question_dbops.class.php.patch.txt)

https://tracker.moodle.org/browse/MDL-55458

**Comment by litall** [comment]
Hello,
The patch didn't solve my problem.
I still get the same error that "Table 'moodle_moodle_f.backup_ids_temp' doesn't exist".

Stack trace:
line 590 of /lib/dml/moodle_database.php: dml_exception thrown
line 1779 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 103 of /backup/util/dbops/backup_structure_dbops.class.php: call to moodle_database->record_exists()
line 58 of /backup/util/structure/backup_final_element.class.php: call to backup_structure_dbops::insert_backup_ids_record()
line 115 of /backup/util/structure/backup_structure_processor.class.php: call to backup_final_element->annotate()
line 38 of /backup/util/structure/backup_final_element.class.php: call to backup_structure_processor->process_final_element()
line 97 of /backup/util/structure/backup_nested_element.class.php: call to backup_final_element->process()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()
line 97 of /backup/util/plan/backup_structure_step.class.php: call to backup_nested_element->process()
line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
line 177 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 120 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
line 320 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
line 136 of /backup/util/ui/backup_ui.class.php: call to backup_controller->execute_plan()
line 131 of /backup/backup.php: call to backup_ui->execute

Thanks a lot!

**Comment by dkuzevanov** [comment]
I am working on this bug.
I will write solution here.
You can read additional info at Moodle tracker.

**Comment by litall** [comment]
Thanks.
I'm looking forward for your solution!

**Comment by dkuzevanov** [comment]
Try this workaround: [backup_restore_fix.patch.txt](https://github.com/dkuzevanov/moodle_master_slave/files/415453/backup_restore_fix.patch.txt)

It fix backup&restore process from UI, does it?

**Comment by dkuzevanov** [comment]
For console: [cli_backup_restore_fix.patch.txt](https://github.com/dkuzevanov/moodle_master_slave/files/415465/cli_backup_restore_fix.patch.txt)

If it works then soon I will make a nice solution.

**Comment by litall** [comment]
Unfortunately its still don't work.

**Comment by dkuzevanov** [comment]
Strange because i successfully made backup and restore course after applying the patches.

**Comment by dkuzevanov** [comment]
Please, remove previous patches and try this last one: [br_patch_last.patch.txt](https://github.com/dkuzevanov/moodle_master_slave/files/424738/br_patch_last.patch.txt)

**Comment by litall** [comment]
Thanks a lot!!
Its works!!

**Comment by dkuzevanov** [comment]
Thank you.
Soon i will push the changes to master.

**Comment by dkuzevanov** [comment]
Pushed.
