### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by eabcdev** [dkuzevanov/moodle_master_slave#3]
Hi, is this project closed? 
I wanted to keep in touch with you in order to implement read splitting with moodle, but I wanted to know this project status, if you have an alternative, or what happened that you did not made commits since 2016.
We tested this with moodle 3.3 and had issues with new functionalities (moodle competencies) so I dont know this driver stability
thanks!

**Comment by dkuzevanov** [comment]
@eabcdev hello!
This version is stable in my project, works fine.
I can help if you provide more info.
Thanx!
